// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(gestorBibliotecaContext))]
    [Migration("20231102121922_migracion4")]
    partial class migracion4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.Property<long>("libro_con_autoresid_autor")
                        .HasColumnType("bigint");

                    b.Property<long>("libros_con_autorid_libro")
                        .HasColumnType("bigint");

                    b.HasKey("libro_con_autoresid_autor", "libros_con_autorid_libro");

                    b.HasIndex("libros_con_autorid_libro");

                    b.ToTable("AutorLibro");
                });

            modelBuilder.Entity("DB.Acceso", b =>
                {
                    b.Property<long>("id_acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_acceso"));

                    b.Property<string>("codigo_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descipcion_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_acceso");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("DB.Autor", b =>
                {
                    b.Property<long>("id_autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_autor"));

                    b.Property<string>("apellidos_autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_autor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_autor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("DB.Coleccion", b =>
                {
                    b.Property<long>("id_coleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_coleccion"));

                    b.Property<string>("nombre_coleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_coleccion");

                    b.ToTable("Colecciones");
                });

            modelBuilder.Entity("DB.Editorial", b =>
                {
                    b.Property<long>("id_editorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_editorial"));

                    b.Property<string>("nombre_editorial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_editorial");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("DB.Estado_Prestamo", b =>
                {
                    b.Property<long>("id_estado_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_estado_prestamo"));

                    b.Property<string>("codigo_estado_prestamo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion_estado_prestamo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_estado_prestamo");

                    b.ToTable("Estados_Prestamos");
                });

            modelBuilder.Entity("DB.Genero", b =>
                {
                    b.Property<long>("id_genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_genero"));

                    b.Property<string>("descripcion_genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_genero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("DB.Libro", b =>
                {
                    b.Property<long>("id_libro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_libro"));

                    b.Property<int>("cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("edicion_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("id_coleccion")
                        .HasColumnType("bigint");

                    b.Property<long>("id_editorial")
                        .HasColumnType("bigint");

                    b.Property<long>("id_genero")
                        .HasColumnType("bigint");

                    b.Property<string>("isbn_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_libro");

                    b.HasIndex("id_coleccion");

                    b.HasIndex("id_editorial");

                    b.HasIndex("id_genero");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("DB.Prestamo", b =>
                {
                    b.Property<long>("id_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_prestamo"));

                    b.Property<DateTime>("fch_entrega_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_fin_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_inicio_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("id_estado_prestamo")
                        .HasColumnType("bigint");

                    b.Property<long>("id_usuario")
                        .HasColumnType("bigint");

                    b.HasKey("id_prestamo");

                    b.HasIndex("id_estado_prestamo");

                    b.HasIndex("id_usuario");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("DB.Usuario", b =>
                {
                    b.Property<long>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("id_usuario"));

                    b.Property<string>("apellidos_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clave_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dni_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estaBloqueado_usuario")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fch_alta_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_baja_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_fin_bloqueo_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("id_acceso")
                        .HasColumnType("bigint");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tlf_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_acceso");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LibroPrestamo", b =>
                {
                    b.Property<long>("libro_con_prestamosid_prestamo")
                        .HasColumnType("bigint");

                    b.Property<long>("libros_de_prestamoid_libro")
                        .HasColumnType("bigint");

                    b.HasKey("libro_con_prestamosid_prestamo", "libros_de_prestamoid_libro");

                    b.HasIndex("libros_de_prestamoid_libro");

                    b.ToTable("LibroPrestamo");
                });

            modelBuilder.Entity("AutorLibro", b =>
                {
                    b.HasOne("DB.Autor", null)
                        .WithMany()
                        .HasForeignKey("libro_con_autoresid_autor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Libro", null)
                        .WithMany()
                        .HasForeignKey("libros_con_autorid_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DB.Libro", b =>
                {
                    b.HasOne("DB.Coleccion", "coleccion")
                        .WithMany("coleccion_con_libros")
                        .HasForeignKey("id_coleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Editorial", "editorial")
                        .WithMany("editorial_con_libros")
                        .HasForeignKey("id_editorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Genero", "genero")
                        .WithMany("genero_con_libros")
                        .HasForeignKey("id_genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coleccion");

                    b.Navigation("editorial");

                    b.Navigation("genero");
                });

            modelBuilder.Entity("DB.Prestamo", b =>
                {
                    b.HasOne("DB.Estado_Prestamo", "estadoConPrestamo")
                        .WithMany("prestamos_con_estado")
                        .HasForeignKey("id_estado_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "usuario")
                        .WithMany("prestamos_de_usuario")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estadoConPrestamo");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("DB.Usuario", b =>
                {
                    b.HasOne("DB.Acceso", "acceso")
                        .WithMany("usuarios_con_acesso")
                        .HasForeignKey("id_acceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("acceso");
                });

            modelBuilder.Entity("LibroPrestamo", b =>
                {
                    b.HasOne("DB.Prestamo", null)
                        .WithMany()
                        .HasForeignKey("libro_con_prestamosid_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Libro", null)
                        .WithMany()
                        .HasForeignKey("libros_de_prestamoid_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DB.Acceso", b =>
                {
                    b.Navigation("usuarios_con_acesso");
                });

            modelBuilder.Entity("DB.Coleccion", b =>
                {
                    b.Navigation("coleccion_con_libros");
                });

            modelBuilder.Entity("DB.Editorial", b =>
                {
                    b.Navigation("editorial_con_libros");
                });

            modelBuilder.Entity("DB.Estado_Prestamo", b =>
                {
                    b.Navigation("prestamos_con_estado");
                });

            modelBuilder.Entity("DB.Genero", b =>
                {
                    b.Navigation("genero_con_libros");
                });

            modelBuilder.Entity("DB.Usuario", b =>
                {
                    b.Navigation("prestamos_de_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
